import SwiftUI

struct ProposalDetailView: View {
    let story: Story
    let chapter: Chapter
    let proposal: Proposal
    @StateObject private var vm: ProposalDetailViewModel
    @State private var commentText = ""

    init(story: Story, chapter: Chapter, proposal: Proposal) {
        self.story = story
        self.chapter = chapter
        self.proposal = proposal
        _vm = StateObject(wrappedValue: ProposalDetailViewModel(story: story, chapter: chapter, proposal: proposal))
    }

    var body: some View {
        List {
            Section {
                if proposal.isAIGenerated {
                    Label("Generated by AI", systemImage: "sparkles")
                        .font(.caption)
                        .foregroundStyle(.purple)
                }
                Text(proposal.text)
                    .font(.body)
            } header: {
                Text("Proposal by \(proposal.authorDisplayName)")
            }

            Section("Discussion") {
                ForEach(vm.comments) { comment in
                    VStack(alignment: .leading, spacing: 4) {
                        Text(comment.authorDisplayName)
                            .font(.caption.bold())
                        Text(comment.text)
                            .font(.subheadline)
                    }
                    .padding(.vertical, 2)
                }

                HStack {
                    TextField("Add a comment…", text: $commentText)
                    Button("Send") {
                        Task { await vm.sendComment(commentText); commentText = "" }
                    }
                    .disabled(commentText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
                }
            }
        }
        .navigationTitle("Proposal")
        .navigationBarTitleDisplayMode(.inline)
        .task { await vm.load() }
    }
}
